{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "b564eede-9507-439e-b626-e0fd6526be1e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Rows generated: 1500\n",
      "\n",
      "Columns:\n",
      "['order_id', 'patient_location', 'priority', 'test_name', 'department', 'instrument', 'specimen_type', 'workflow_type', 'order_time', 'collect_time', 'receive_time', 'instrument_result_time', 'final_result_time', 'downstream_post_status', 'verification_status', 'result_status', 'delay_reason', 'tat_collection_min', 'tat_transport_min', 'tat_lab_min', 'tat_result_post_min', 'tat_total_min', 'tat_total_hours', 'collection_delay_flag', 'transport_delay_flag', 'lab_delay_flag', 'result_post_delay_flag', 'stat_delay_flag']\n",
      "\n",
      "Sample rows:\n",
      "   order_id patient_location priority          test_name    department  \\\n",
      "0         1              ICU     STAT      Wound Culture  Microbiology   \n",
      "1         2             FSED     STAT      Urine Culture  Microbiology   \n",
      "2         3               ED  Routine  Respiratory Panel     Molecular   \n",
      "3         4             FSED  Routine      COVID/Flu PCR     Molecular   \n",
      "4         5          MedSurg  Routine      Blood Culture  Microbiology   \n",
      "\n",
      "       instrument        specimen_type workflow_type  \\\n",
      "0  Manual Culture                Wound       Culture   \n",
      "1  Manual Culture                Urine       Culture   \n",
      "2         BioFire  Nasopharyngeal Swab     Molecular   \n",
      "3          ID NOW           Nasal Swab     Molecular   \n",
      "4          BACTEC                Blood       Culture   \n",
      "\n",
      "                  order_time               collect_time  ...  \\\n",
      "0 2026-04-19 03:44:36.866791 2026-04-19 03:56:36.866791  ...   \n",
      "1 2026-04-20 13:55:36.867012 2026-04-20 14:22:36.867012  ...   \n",
      "2 2026-04-03 00:36:36.867154 2026-04-03 00:52:36.867154  ...   \n",
      "3 2026-04-06 14:59:36.867301 2026-04-06 16:05:36.867301  ...   \n",
      "4 2026-03-31 23:38:36.867432 2026-04-01 00:13:36.867432  ...   \n",
      "\n",
      "  tat_transport_min tat_lab_min tat_result_post_min tat_total_min  \\\n",
      "0               8.0      3673.0                 1.0        3694.0   \n",
      "1              58.0      1649.0                 3.0        1737.0   \n",
      "2              13.0       148.0                 8.0         185.0   \n",
      "3             529.0       118.0               119.0         832.0   \n",
      "4              46.0      1012.0                 4.0        1097.0   \n",
      "\n",
      "  tat_total_hours collection_delay_flag transport_delay_flag  lab_delay_flag  \\\n",
      "0       61.566667                     N                    N               Y   \n",
      "1       28.950000                     N                    N               Y   \n",
      "2        3.083333                     N                    N               N   \n",
      "3       13.866667                     Y                    Y               N   \n",
      "4       18.283333                     N                    N               Y   \n",
      "\n",
      "   result_post_delay_flag  stat_delay_flag  \n",
      "0                       N                Y  \n",
      "1                       N                Y  \n",
      "2                       N                N  \n",
      "3                       Y                N  \n",
      "4                       N                N  \n",
      "\n",
      "[5 rows x 28 columns]\n",
      "\n",
      "Average TAT by location (hours):\n",
      "patient_location\n",
      "ED             15.44\n",
      "FSED           20.70\n",
      "ICU            19.65\n",
      "MedSurg        19.37\n",
      "Oncology       19.38\n",
      "PrimaryCare    23.23\n",
      "Name: tat_total_hours, dtype: float64\n",
      "\n",
      "Delay reasons:\n",
      "delay_reason\n",
      "None                                                           1282\n",
      "Courier batching delay                                          100\n",
      "Instrument queue or manual handling                              94\n",
      "Courier batching delay; Instrument queue or manual handling      10\n",
      "Tube station or runner delay                                      9\n",
      "Specimen collection delay                                         4\n",
      "Specimen collection delay; Tube station or runner delay           1\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Transport delay flags by location and priority:\n",
      "transport_delay_flag         N    Y\n",
      "patient_location priority          \n",
      "ED               Routine   193    0\n",
      "                 STAT       61    5\n",
      "FSED             Routine   116  100\n",
      "                 STAT       27   13\n",
      "ICU              Routine   194    0\n",
      "                 STAT       33    5\n",
      "MedSurg          Routine   170    0\n",
      "                 STAT       41    0\n",
      "Oncology         Routine   201    0\n",
      "                 STAT       51    0\n",
      "PrimaryCare      Routine    65  171\n",
      "                 STAT       49    5\n",
      "\n",
      "Downstream post status counts:\n",
      "downstream_post_status\n",
      "posted_on_time      1385\n",
      "delayed_posting       82\n",
      "manual_follow_up      33\n",
      "Name: count, dtype: int64\n",
      "\n",
      "CSV exported as: output\\microbiology_workflow_analysis_dataset.csv\n"
     ]
    }
   ],
   "source": [
    "#!/usr/bin/env python\n",
    "# coding: utf-8\n",
    "\n",
    "\"\"\"\n",
    "Microbiology workflow analysis dataset generator\n",
    "Portfolio section: 01_workflow-analysis\n",
    "\n",
    "Purpose\n",
    "-------\n",
    "Generate a synthetic microbiology / molecular dataset that models the\n",
    "order-to-result lifecycle in an Epic Beaker-aligned lab workflow project.\n",
    "\n",
    "This version is intentionally framed for the workflow-analysis section of the\n",
    "portfolio. It emphasizes:\n",
    "- order -> collect -> receive -> instrument result -> final result\n",
    "- turnaround-time segmentation\n",
    "- event flags for workflow bottlenecks\n",
    "- location- and priority-driven delay patterns\n",
    "- controlled real-world variability\n",
    "\"\"\"\n",
    "\n",
    "from __future__ import annotations\n",
    "\n",
    "import random\n",
    "from dataclasses import dataclass, asdict\n",
    "from datetime import datetime, timedelta\n",
    "from pathlib import Path\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# CONFIGURATION\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "OUTPUT_DIR = Path(\"output\")\n",
    "OUTPUT_FILE = OUTPUT_DIR / \"microbiology_workflow_analysis_dataset.csv\"\n",
    "NUM_ORDERS = 1500\n",
    "LOOKBACK_DAYS = 30\n",
    "RANDOM_SEED = 42\n",
    "\n",
    "random.seed(RANDOM_SEED)\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# REFERENCE DATA\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "TEST_CATALOG = [\n",
    "    {\n",
    "        \"test_name\": \"COVID/Flu PCR\",\n",
    "        \"department\": \"Molecular\",\n",
    "        \"instrument\": \"ID NOW\",\n",
    "        \"specimen_type\": \"Nasal Swab\",\n",
    "        \"workflow_type\": \"Molecular\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"C. Diff PCR\",\n",
    "        \"department\": \"Molecular\",\n",
    "        \"instrument\": \"Revogene\",\n",
    "        \"specimen_type\": \"Stool\",\n",
    "        \"workflow_type\": \"Molecular\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"Respiratory Panel\",\n",
    "        \"department\": \"Molecular\",\n",
    "        \"instrument\": \"BioFire\",\n",
    "        \"specimen_type\": \"Nasopharyngeal Swab\",\n",
    "        \"workflow_type\": \"Molecular\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"Blood Culture\",\n",
    "        \"department\": \"Microbiology\",\n",
    "        \"instrument\": \"BACTEC\",\n",
    "        \"specimen_type\": \"Blood\",\n",
    "        \"workflow_type\": \"Culture\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"Urine Culture\",\n",
    "        \"department\": \"Microbiology\",\n",
    "        \"instrument\": \"Manual Culture\",\n",
    "        \"specimen_type\": \"Urine\",\n",
    "        \"workflow_type\": \"Culture\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"Wound Culture\",\n",
    "        \"department\": \"Microbiology\",\n",
    "        \"instrument\": \"Manual Culture\",\n",
    "        \"specimen_type\": \"Wound\",\n",
    "        \"workflow_type\": \"Culture\",\n",
    "    },\n",
    "    {\n",
    "        \"test_name\": \"MRSA Screen\",\n",
    "        \"department\": \"Microbiology\",\n",
    "        \"instrument\": \"BD Max\",\n",
    "        \"specimen_type\": \"Nasal Swab\",\n",
    "        \"workflow_type\": \"Molecular\",\n",
    "    },\n",
    "]\n",
    "\n",
    "PATIENT_LOCATIONS = [\"ICU\", \"ED\", \"MedSurg\", \"Oncology\", \"FSED\", \"PrimaryCare\"]\n",
    "PRIORITIES = [\"STAT\", \"Routine\"]\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# DATA MODEL\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "@dataclass\n",
    "class WorkflowOrder:\n",
    "    order_id: int\n",
    "    patient_location: str\n",
    "    priority: str\n",
    "    test_name: str\n",
    "    department: str\n",
    "    instrument: str\n",
    "    specimen_type: str\n",
    "    workflow_type: str\n",
    "    order_time: datetime\n",
    "    collect_time: datetime\n",
    "    receive_time: datetime\n",
    "    instrument_result_time: datetime\n",
    "    final_result_time: datetime\n",
    "    downstream_post_status: str\n",
    "    verification_status: str\n",
    "    result_status: str\n",
    "\n",
    "    # NEW: adds a portfolio-friendly field for troubleshooting analysis\n",
    "    delay_reason: str\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# HELPER FUNCTIONS\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "def random_order_time() -> datetime:\n",
    "    \"\"\"Generate a random order time within the last N days.\"\"\"\n",
    "    now = datetime.now()\n",
    "    days_back = random.randint(0, LOOKBACK_DAYS - 1)\n",
    "    minutes_back = random.randint(0, 23 * 60 + 59)\n",
    "    return now - timedelta(days=days_back, minutes=minutes_back)\n",
    "\n",
    "\n",
    "def get_collection_delay(location: str, priority: str) -> int:\n",
    "    \"\"\"Return baseline specimen collection delay in minutes.\"\"\"\n",
    "    if priority == \"STAT\":\n",
    "        return random.randint(5, 30)\n",
    "\n",
    "    if location in [\"ICU\", \"ED\"]:\n",
    "        return random.randint(10, 45)\n",
    "    if location == \"FSED\":\n",
    "        return random.randint(20, 90)\n",
    "    if location == \"PrimaryCare\":\n",
    "        return random.randint(30, 180)\n",
    "\n",
    "    return random.randint(15, 90)\n",
    "\n",
    "\n",
    "def get_transport_delay(location: str, priority: str) -> int:\n",
    "    \"\"\"Return baseline specimen transport / receipt delay in minutes.\"\"\"\n",
    "    if priority == \"STAT\":\n",
    "        if location in [\"ICU\", \"ED\"]:\n",
    "            return random.randint(5, 20)\n",
    "        if location == \"FSED\":\n",
    "            return random.randint(30, 120)\n",
    "        return random.randint(15, 60)\n",
    "\n",
    "    if location in [\"ICU\", \"ED\"]:\n",
    "        return random.randint(10, 40)\n",
    "    if location == \"FSED\":\n",
    "        return random.randint(60, 240)\n",
    "    if location == \"PrimaryCare\":\n",
    "        return random.randint(120, 480)\n",
    "\n",
    "    return random.randint(20, 90)\n",
    "\n",
    "\n",
    "def get_lab_processing_delay(test_name: str, workflow_type: str, priority: str) -> int:\n",
    "    \"\"\"Return baseline lab processing delay in minutes.\"\"\"\n",
    "    if workflow_type == \"Molecular\":\n",
    "        if priority == \"STAT\":\n",
    "            return random.randint(30, 120)\n",
    "        return random.randint(60, 240)\n",
    "\n",
    "    if test_name == \"Blood Culture\":\n",
    "        return random.randint(720, 2880)\n",
    "    if test_name == \"Urine Culture\":\n",
    "        return random.randint(1080, 2880)\n",
    "    if test_name == \"Wound Culture\":\n",
    "        return random.randint(1440, 4320)\n",
    "\n",
    "    return random.randint(60, 240)\n",
    "\n",
    "\n",
    "# NEW: adds controlled real-world messiness to the dataset\n",
    "def apply_operational_variability(\n",
    "    base_minutes: int,\n",
    "    location: str,\n",
    "    priority: str,\n",
    "    stage: str,\n",
    ") -> tuple[int, str]:\n",
    "    \"\"\"\n",
    "    Add rare but realistic operational exceptions.\n",
    "\n",
    "    This prevents the synthetic dataset from being too clean.\n",
    "    It especially helps avoid scenarios where ED/ICU STAT orders have zero delays.\n",
    "    \"\"\"\n",
    "\n",
    "    roll = random.random()\n",
    "\n",
    "    # NEW: ED/ICU STAT specimens usually move quickly,\n",
    "    # but occasional real-world exceptions should exist.\n",
    "    if location in [\"ED\", \"ICU\"] and priority == \"STAT\":\n",
    "        if stage == \"transport\" and roll < 0.08:\n",
    "            return base_minutes + random.randint(90, 240), \"Tube station or runner delay\"\n",
    "\n",
    "        if stage == \"collection\" and roll < 0.05:\n",
    "            return base_minutes + random.randint(45, 120), \"Specimen collection delay\"\n",
    "\n",
    "    # NEW: FSED and PrimaryCare are more vulnerable to courier batching.\n",
    "    if location in [\"FSED\", \"PrimaryCare\"]:\n",
    "        if stage == \"transport\" and roll < 0.20:\n",
    "            return base_minutes + random.randint(120, 360), \"Courier batching delay\"\n",
    "\n",
    "    # NEW: occasional lab processing delay regardless of location.\n",
    "    if stage == \"lab\" and roll < 0.07:\n",
    "        return base_minutes + random.randint(60, 240), \"Instrument queue or manual handling\"\n",
    "\n",
    "    return base_minutes, \"None\"\n",
    "\n",
    "\n",
    "def get_result_post_delay() -> tuple[int, str]:\n",
    "    \"\"\"\n",
    "    Simulate downstream result-posting delay.\n",
    "\n",
    "    This keeps a bridge to future system-integration work without making\n",
    "    middleware/interface logic the main focus of this project.\n",
    "    \"\"\"\n",
    "    roll = random.random()\n",
    "\n",
    "    if roll < 0.92:\n",
    "        return random.randint(1, 10), \"posted_on_time\"\n",
    "    if roll < 0.98:\n",
    "        return random.randint(15, 60), \"delayed_posting\"\n",
    "\n",
    "    return random.randint(60, 240), \"manual_follow_up\"\n",
    "\n",
    "\n",
    "def get_verification_status(workflow_type: str, downstream_post_status: str) -> str:\n",
    "    \"\"\"Return auto/manual verification status.\"\"\"\n",
    "    if downstream_post_status == \"manual_follow_up\":\n",
    "        return \"Manual\"\n",
    "\n",
    "    if workflow_type == \"Molecular\":\n",
    "        return random.choices([\"Auto\", \"Manual\"], weights=[75, 25], k=1)[0]\n",
    "\n",
    "    return random.choices([\"Auto\", \"Manual\"], weights=[25, 75], k=1)[0]\n",
    "\n",
    "\n",
    "def get_result_status(downstream_post_status: str) -> str:\n",
    "    \"\"\"Return final result status.\"\"\"\n",
    "    if downstream_post_status == \"manual_follow_up\":\n",
    "        return random.choice([\"Corrected\", \"Final\"])\n",
    "\n",
    "    return random.choice([\"Preliminary\", \"Final\"])\n",
    "\n",
    "\n",
    "# NEW: combines multiple delay reasons cleanly\n",
    "def combine_delay_reasons(reasons: list[str]) -> str:\n",
    "    \"\"\"\n",
    "    Combine non-None delay reasons into one readable field.\n",
    "    \"\"\"\n",
    "    active_reasons = [reason for reason in reasons if reason != \"None\"]\n",
    "\n",
    "    if not active_reasons:\n",
    "        return \"None\"\n",
    "\n",
    "    return \"; \".join(active_reasons)\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# GENERATION LOGIC\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "def build_orders(num_orders: int = NUM_ORDERS) -> pd.DataFrame:\n",
    "    \"\"\"Generate the synthetic workflow dataset.\"\"\"\n",
    "    orders: list[dict] = []\n",
    "\n",
    "    for order_id in range(1, num_orders + 1):\n",
    "        test = random.choice(TEST_CATALOG)\n",
    "        location = random.choice(PATIENT_LOCATIONS)\n",
    "        priority = random.choices(PRIORITIES, weights=[20, 80], k=1)[0]\n",
    "\n",
    "        order_time = random_order_time()\n",
    "\n",
    "        # CHANGED: delays are now generated in two steps:\n",
    "        # 1. baseline delay\n",
    "        # 2. operational variability layered on top\n",
    "\n",
    "        baseline_collection_delay = get_collection_delay(location, priority)\n",
    "        collection_delay, collection_reason = apply_operational_variability(\n",
    "            base_minutes=baseline_collection_delay,\n",
    "            location=location,\n",
    "            priority=priority,\n",
    "            stage=\"collection\",\n",
    "        )\n",
    "\n",
    "        baseline_transport_delay = get_transport_delay(location, priority)\n",
    "        transport_delay, transport_reason = apply_operational_variability(\n",
    "            base_minutes=baseline_transport_delay,\n",
    "            location=location,\n",
    "            priority=priority,\n",
    "            stage=\"transport\",\n",
    "        )\n",
    "\n",
    "        baseline_lab_delay = get_lab_processing_delay(\n",
    "            test_name=test[\"test_name\"],\n",
    "            workflow_type=test[\"workflow_type\"],\n",
    "            priority=priority,\n",
    "        )\n",
    "        lab_delay, lab_reason = apply_operational_variability(\n",
    "            base_minutes=baseline_lab_delay,\n",
    "            location=location,\n",
    "            priority=priority,\n",
    "            stage=\"lab\",\n",
    "        )\n",
    "\n",
    "        collect_time = order_time + timedelta(minutes=collection_delay)\n",
    "        receive_time = collect_time + timedelta(minutes=transport_delay)\n",
    "        instrument_result_time = receive_time + timedelta(minutes=lab_delay)\n",
    "\n",
    "        result_post_delay, downstream_post_status = get_result_post_delay()\n",
    "        final_result_time = instrument_result_time + timedelta(minutes=result_post_delay)\n",
    "\n",
    "        verification_status = get_verification_status(\n",
    "            workflow_type=test[\"workflow_type\"],\n",
    "            downstream_post_status=downstream_post_status,\n",
    "        )\n",
    "\n",
    "        result_status = get_result_status(downstream_post_status)\n",
    "\n",
    "        # NEW: delay reason supports SQL grouping and troubleshooting summaries.\n",
    "        delay_reason = combine_delay_reasons(\n",
    "            [collection_reason, transport_reason, lab_reason]\n",
    "        )\n",
    "\n",
    "        order = WorkflowOrder(\n",
    "            order_id=order_id,\n",
    "            patient_location=location,\n",
    "            priority=priority,\n",
    "            test_name=test[\"test_name\"],\n",
    "            department=test[\"department\"],\n",
    "            instrument=test[\"instrument\"],\n",
    "            specimen_type=test[\"specimen_type\"],\n",
    "            workflow_type=test[\"workflow_type\"],\n",
    "            order_time=order_time,\n",
    "            collect_time=collect_time,\n",
    "            receive_time=receive_time,\n",
    "            instrument_result_time=instrument_result_time,\n",
    "            final_result_time=final_result_time,\n",
    "            downstream_post_status=downstream_post_status,\n",
    "            verification_status=verification_status,\n",
    "            result_status=result_status,\n",
    "            delay_reason=delay_reason,\n",
    "        )\n",
    "\n",
    "        orders.append(asdict(order))\n",
    "\n",
    "    return pd.DataFrame(orders)\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# DERIVED METRICS\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "def add_workflow_metrics(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"Add segmented turnaround-time metrics.\"\"\"\n",
    "    df = df.copy()\n",
    "\n",
    "    df[\"tat_collection_min\"] = (\n",
    "        df[\"collect_time\"] - df[\"order_time\"]\n",
    "    ).dt.total_seconds() / 60\n",
    "\n",
    "    df[\"tat_transport_min\"] = (\n",
    "        df[\"receive_time\"] - df[\"collect_time\"]\n",
    "    ).dt.total_seconds() / 60\n",
    "\n",
    "    df[\"tat_lab_min\"] = (\n",
    "        df[\"instrument_result_time\"] - df[\"receive_time\"]\n",
    "    ).dt.total_seconds() / 60\n",
    "\n",
    "    df[\"tat_result_post_min\"] = (\n",
    "        df[\"final_result_time\"] - df[\"instrument_result_time\"]\n",
    "    ).dt.total_seconds() / 60\n",
    "\n",
    "    df[\"tat_total_min\"] = (\n",
    "        df[\"final_result_time\"] - df[\"order_time\"]\n",
    "    ).dt.total_seconds() / 60\n",
    "\n",
    "    df[\"tat_total_hours\"] = df[\"tat_total_min\"] / 60\n",
    "\n",
    "    # CLEANUP: removed duplicate stat_delay_flag logic from this function.\n",
    "    # It is now only created in add_event_flags().\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# EVENT FLAGS\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "# NEW: context-aware transport delay flag\n",
    "def get_transport_delay_flag(row: pd.Series) -> str:\n",
    "    \"\"\"\n",
    "    Flag transport delays using location- and priority-aware thresholds.\n",
    "\n",
    "    This is more realistic than using one flat threshold for every workflow.\n",
    "    \"\"\"\n",
    "\n",
    "    if row[\"priority\"] == \"STAT\" and row[\"patient_location\"] in [\"ED\", \"ICU\"]:\n",
    "        return \"Y\" if row[\"tat_transport_min\"] > 45 else \"N\"\n",
    "\n",
    "    if row[\"patient_location\"] == \"FSED\":\n",
    "        return \"Y\" if row[\"tat_transport_min\"] > 180 else \"N\"\n",
    "\n",
    "    if row[\"patient_location\"] == \"PrimaryCare\":\n",
    "        return \"Y\" if row[\"tat_transport_min\"] > 240 else \"N\"\n",
    "\n",
    "    return \"Y\" if row[\"tat_transport_min\"] > 120 else \"N\"\n",
    "\n",
    "\n",
    "def add_event_flags(df: pd.DataFrame) -> pd.DataFrame:\n",
    "    \"\"\"Add event-style workflow flags for bottleneck detection.\"\"\"\n",
    "    df = df.copy()\n",
    "\n",
    "    df[\"collection_delay_flag\"] = df[\"tat_collection_min\"].apply(\n",
    "        lambda x: \"Y\" if x > 60 else \"N\"\n",
    "    )\n",
    "\n",
    "    # CHANGED: replaced one flat threshold with context-aware function.\n",
    "    df[\"transport_delay_flag\"] = df.apply(get_transport_delay_flag, axis=1)\n",
    "\n",
    "    df[\"lab_delay_flag\"] = df[\"tat_lab_min\"].apply(\n",
    "        lambda x: \"Y\" if x > 240 else \"N\"\n",
    "    )\n",
    "\n",
    "    df[\"result_post_delay_flag\"] = df[\"tat_result_post_min\"].apply(\n",
    "        lambda x: \"Y\" if x > 30 else \"N\"\n",
    "    )\n",
    "\n",
    "    df[\"stat_delay_flag\"] = df.apply(\n",
    "        lambda row: \"Y\"\n",
    "        if row[\"priority\"] == \"STAT\" and row[\"tat_total_min\"] > 180\n",
    "        else \"N\",\n",
    "        axis=1,\n",
    "    )\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# EXPORT + QA\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "def export_dataset(df: pd.DataFrame, output_file: Path = OUTPUT_FILE) -> None:\n",
    "    \"\"\"Write dataset to CSV.\"\"\"\n",
    "    output_file.parent.mkdir(parents=True, exist_ok=True)\n",
    "    df.to_csv(output_file, index=False)\n",
    "\n",
    "\n",
    "def run_data_quality_checks(df: pd.DataFrame) -> None:\n",
    "    \"\"\"Display quick validation checks.\"\"\"\n",
    "    print(\"Rows generated:\", len(df))\n",
    "\n",
    "    print(\"\\nColumns:\")\n",
    "    print(df.columns.tolist())\n",
    "\n",
    "    print(\"\\nSample rows:\")\n",
    "    print(df.head())\n",
    "\n",
    "    print(\"\\nAverage TAT by location (hours):\")\n",
    "    print(df.groupby(\"patient_location\")[\"tat_total_hours\"].mean().round(2))\n",
    "\n",
    "    print(\"\\nDelay reasons:\")\n",
    "    print(df[\"delay_reason\"].value_counts())\n",
    "\n",
    "    print(\"\\nTransport delay flags by location and priority:\")\n",
    "    print(\n",
    "        df.groupby([\"patient_location\", \"priority\"])[\"transport_delay_flag\"]\n",
    "        .value_counts()\n",
    "        .unstack(fill_value=0)\n",
    "    )\n",
    "\n",
    "    print(\"\\nDownstream post status counts:\")\n",
    "    print(df[\"downstream_post_status\"].value_counts())\n",
    "\n",
    "    print(f\"\\nCSV exported as: {OUTPUT_FILE}\")\n",
    "\n",
    "\n",
    "def main() -> None:\n",
    "    df = build_orders()\n",
    "    df = add_workflow_metrics(df)\n",
    "    df = add_event_flags(df)\n",
    "    export_dataset(df)\n",
    "    run_data_quality_checks(df)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
